# Config file for "THE LEGEND OF ZELDA " Recompilation.

[input]
entrypoint = 0x80000400
# Paths are relative to the location of this config file.
elf_path = "lib/indigo/zelda_ocarina_mq_dbg.elf"
output_func_path = "RecompiledFuncs"
relocatable_sections_path = "overlays.txt"

[patches]
stubs = [
    # None
]

ignored = [
    # This is only a dummy function to inform recomp about overlay loading
    "RECOMP_load_overlays_recomp",
    # These are supposed to be corrupted and corrupted_init in pfschecker.c but they aren't named yet so aren't auto-ignored
    "func_80105788",
    "func_80105A60",
]
